export const SRI_LANKAN_INSTITUTES = [
  // HND / SLIATE ATIs
  "Advanced Technological Institute (ATI) - Ampara",
  "Advanced Technological Institute (ATI) - Anuradhapura",
  "Advanced Technological Institute (ATI) - Badulla",
  "Advanced Technological Institute (ATI) - Batticaloa",
  "Advanced Technological Institute (ATI) - Colombo (Dehiwala)",
  "Advanced Technological Institute (ATI) - Galle (Labuduwa)",
  "Advanced Technological Institute (ATI) - Gampaha (Naiwala)",
  "Advanced Technological Institute (ATI) - Jaffna",
  "Advanced Technological Institute (ATI) - Kandy (Sucharithagama)",
  "Advanced Technological Institute (ATI) - Kegalle",
  "Advanced Technological Institute (ATI) - Kurunegala",
  "Advanced Technological Institute (ATI) - Mannar",
  "Advanced Technological Institute (ATI) - Trincomalee",
  "Advanced Technological Institute (ATI) - Vavuniya",
  "Advanced Technological Institute (ATI) - Ratnapura",
  "Advanced Technological Institute (ATI) - Kalutara",
  "Advanced Technological Institute (ATI) - Matara",
  "Advanced Technological Institute (ATI) - Mullaitivu",
  "Advanced Technological Institute (ATI) - Tangalle",

  // Vocational & Open Universities
  "University of Vocational Technology (UNIVOTEC)",
  "The Open University of Sri Lanka (OUSL)",
  "Ocean University of Sri Lanka",

  // Government Universities
  "University of Colombo",
  "University of Moratuwa",
  "University of Peradeniya",
  "University of Kelaniya",
  "University of Sri Jayewardenepura",
  "University of Ruhuna",
  "Sabaragamuwa University of Sri Lanka",
  "Rajarata University of Sri Lanka",
  "Wayamba University of Sri Lanka",
  "Eastern University, Sri Lanka",
  "South Eastern University of Sri Lanka",
  "University of Jaffna",
  "The Open University of Sri Lanka (OUSL)",
  "University of Vocational Technology (UNIVOTEC)",
  "Ocean University of Sri Lanka",
  "Uva Wellassa University",
  "University of the Visual and Performing Arts",
  "Gampaha Wickramarachchi University of Indigenous Medicine",
  "Vavuniya University of Sri Lanka",
  "General Sir John Kotelawala Defence University (KDU)",
  "Sri Lanka Technological Campus (SLTC) / Green University",

  // Major Private Institutes
  "Sri Lanka Institute of Information Technology (SLIIT)",
  "National School of Business Management (NSBM)",
  "Informatics Institute of Technology (IIT)",
  "Sri Lanka Institute of Technological Studies (SLTech)",
  "CINEC Campus",
  "Horizon Campus",
  "KIU Campus",
];
